/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/brain.glb -T 
Files: public/models/brain.glb [68.98KB] > C:\coding_space\final_project\app-frontend\brain-transformed.glb [14.44KB] (79%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/brain-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Brain_Model.geometry} material={nodes.Brain_Model.material} />
    </group>
  )
}

useGLTF.preload('/brain-transformed.glb')
